### ISSUE TITLE
Abnormal

### ISSUE THREAD

**Issue by Shao-JinEi** [legendnightt/MCDR-Translator#1]
now the plugin is not work normaly

just like this ![hello](https://github.com/Shao-JinEi/pocket/blob/main/hello.png)

here is the report

![report](https://github.com/Shao-JinEi/pocket/blob/main/bug.png)

```
[Server] [15:11:57] [Server thread/INFO]: <Shao_JinEi> t hello
[MCDR] [15:11:57] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=translator@1.0.0,priority=1000,callback=<function on_info at 0x00000276C5B06280>]
Traceback (most recent call last):
  File "C:\Users\24371\AppData\Local\Programs\Python\Python39\lib\site-packages\google_trans_new\google_trans_new.py", line 234, in detect
    response = json.loads(response)
  File "C:\Users\24371\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\24371\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 670 (char 669)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\24371\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 474, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\24371\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\Translator.py", line 27, in on_info
    server.say(f'§7[T]<{info.player}> §f{translatorA(info.content[2:])}')
  File "plugins\Translator.py", line 17, in translatorA
    translation = translator.detect(msg)
  File "C:\Users\24371\AppData\Local\Programs\Python\Python39\lib\site-packages\google_trans_new\google_trans_new.py", line 240, in detect
    raise Exception
Exception
>
```

**Comment by skuzow** [comment]
Fixed in [v1.1.0 release](https://github.com/legendnightt/MCDR-Translator/releases/tag/v1.1.0), also googletranslator lib changed so take that in mind!
Plugin uses [googletrans==4.0.0rc1](https://pypi.org/project/googletrans/4.0.0rc1) now.
